Actualización de estilos y funcionalidad de vista de empresas específicas.
Marquinho1775/BMT-PI pull request #30
Opened 2024-10-24 05:01 UTC by Marquinho1775

Se actualiza la vista de cada empresa específica, implementando los nuevos datos obtenidos (Correo y teléfono) además de la funcionalidad para que muestre los productos registrados a esa empresa en específico. Se realiza la actualización siguiendo los nuevos estilos propuestos con el fin de mantener consistencia.

2024-10-24 05:58 UTC, d4v7d approved these changes
Cumple con lo que se pidió

2024-10-24 22:03 UTC, BrandonTrigueros requested changes

2024-10-24 22:03 UTC, BrandonTrigueros commented on frontend/bmt-frontend/src/components/EnterpriseDashboard.vue
Esta tabla podría verse más bonita también me gustaría que la vista de los productos de la empresa sea diferente a la de la homepage (una tabla dedicada).  Además el grid de componente global tiene las acciones del grid del homepage (añádir al carrito)

2024-10-24 22:03 UTC, BrandonTrigueros commented on frontend/bmt-frontend/src/components/EnterpriseDashboard.vue
Además como empresea existen atributos del producto que si me gustaría ver como por ejemplo el peso de los productos

2024-10-25 02:26 UTC, merged

2024-10-25 02:28 UTC, Marquinho1775 commented on frontend/bmt-frontend/src/components/EnterpriseDashboard.vue
Se actualiza diseño y Frontend basado en el mockup aprobado por el Product Owner, adjunto a la user story https://bmtpi.atlassian.net/browse/BMT-57
Se implementa una nueva vista para los productos dentro de la empresa específica, con los datos requeridos, además de mostrar tags solo en caso de tenerlos. Se implementa un sistema de paginación de productos a mano para que solo muestre tres por página. 
Funcionalidad probada para productos con y sin tags y para productos con y sin fotos.